CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(500) NOT NULL,
	ISACTIVE BOOL NOT NULL DEFAULT true,
	DELETED INT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX UK_USERS_USERNAME_DELETED ON USERS (USERNAME, DELETED);